export const COURSE_NAMES: Record<string, string> = {
  ITGE102: "Digital Mindfulness and Time Management",
  ITGE103: "Problem Solving Techniques",
  ITGE141: "Digital Photography",
  ITGE142: "Digital Drawing and Painting",
  ITGE145: "E-Sport and Content Streaming",
  ITGE146: "Creative Thinking",
  ITGE159: "Software Lab for Basic Scientific Problem Solving",
  ITGE161: "Inter-cultural Awareness",
  ITGE162: "Physical Science and Computation",
  ITGE163: "Research Methodology",
  ITGE164: "Computer Application in Biology",
  ITGE165: "Computer Application in Chemistry",
  ITGE182: "Cybersecurity Awareness",
  ITGE183: "Social Issues and Professional Practices",
  ITGE271: "Creating Professional Team Working",
  ITGE272: "Professional Productivity Application",
  ITGE274: "Basic Accounting",
  ITGE275: "Economics",
  ITGE276: "Management",
  ITGE277: "Digital Marketing",
  ITGE301: "Communication Strategies in Professional Life",

  ITLG111: "Technical English I",
  ITLG112: "Listening and Speaking I",
  ITLG113: "English for Content Creation",
  ITLG114: "English for IELTS Test Intermediate",
  ITLG115: "English for TOEFL Test Intermediate",
  ITLG116: "English for TOEIC Intermediate",
  ITLG121: "Reading Skills",
  ITLG122: "Listening and Speaking II",
  ITLG123: "English Preparation for IT Studies",
  ITLG124: "English for IELTS Test Advanced",
  ITLG125: "English for TOEFL Test Advanced",
  ITLG126: "English for TOEIC Advanced",
  ITLG211: "Technical English II",
  ITLG213: "Elementary German I",
  ITLG214: "Elementary Japanese I",
  ITLG215: "Elementary Chinese I",
  ITLG221: "Public Speaking and Presentation",
  ITLG222: "Technical English III",
  ITLG223: "Elementary German II",
  ITLG224: "Elementary Japanese II",
  ITLG225: "Elementary Chinese II",
  ITLG311: "Business Communication",
  ITLG312: "Advanced Reading",
  ITLG313: "Advanced Public Speaking and Presentations",
  ITLG321: "Academic Writing",
  ITLG322: "Special Topics in Reading and Writing",
  ITLG412: "Advanced Technical Writing",

  ITCS111: "Linear Algebra and Calculus for Computing",
  ITCS112: "Discrete Structures",
  ITCS113: "Fundamentals of Programming",
  ITCS114: "Introduction to Computer Ethics",
  ITCS121: "Probability and Statistics for Computing",
  ITCS122: "Numerical Methods",
  ITCS123: "Object Oriented Programming",
  ITCS124: "Introduction to Digital Systems",
  ITCS126: "Introduction to Entrepreneurship",
  ITCS213: "Computer Organization and Architecture",
  ITCS214: "Data Structures and Algorithm Analysis",
  ITCS215: "Introduction to Interactive Multimedia Technology",
  ITCS216: "Fundamentals of Database Systems",
  ITCS217: "Computer Data Communication",
  ITCS223: "Introduction to Web Development",
  ITCS224: "Fundamentals of Information Systems and Software Development",
  ITCS225: "Principles of Operating Systems",
  ITCS226: "Introduction to Computer Network",
  ITCS227: "Introduction to Data Science",
  ITCS247: "Front-end Application Development",
  ITCS248: "Back-end Application Development",
  ITCS249: "Mobile Application Development",
  ITCS250: "System Deployment Lab",
  ITCS311: "Computer and Business Ethics",
  ITCS312: "Computer and Communication Security",
  ITCS313: "Entrepreneurial Practice",
  ITCS314: "Introduction to Experience Design",
  ITCS315: "Introduction to Animation Technology and Basic 2-D Assets",
  ITCS321: "Digital Storytelling and Visual Design",
  ITCS322: "Virtual Reality",
  ITCS324: "Special Topics in Interactive Multimedia Technology",
  ITCS325: "Data Visualization",
  ITCS327: "Assistive Technology and Accessibility",
  ITCS328: "Introduction to Animation Technology and Basic 3-D Assets",
  ITCS331: "Organization of Programming Languages",
  ITCS338: "Foundations in Computer Science",
  ITCS339: "Technology for Game Development",
  ITCS340: "Introduction to Machine Learning",
  ITCS342: "Introduction to Artificial Intelligence",
  ITCS344: "Game-Level Development",
  ITCS345: "Game Logic and Game Play Development",
  ITCS346: "Time Series Analysis",
  ITCS347: "Recommendation System",
  ITCS348: "Introduction to Natural Language Processing",
  ITCS349: "Graph Mining",
  ITCS350: "Advanced Machine Learning Paradigms",
  ITCS351: "Introduction to Computer Vision",
  ITCS352: "Deep Learning",
  ITCS355: "Machine Learning Operation and Deployment",
  ITCS357: "Content-Based Search Engines",
  ITCS358: "Affective Computing Basic",
  ITCS368: "Information and Business Process Management",
  ITCS379: "Practical Software Engineering",
  ITCS380: "Information Systems Management",
  ITCS382: "Software Design and Modelling",
  ITCS383: "Software Construction and Evolution",
  ITCS384: "Software Process and Quality Assurance",
  ITCS385: "Software Architecture",
  ITCS386: "Software Verification and Validation",
  ITCS387: "Project Management and Practice",
  ITCS390: "Competitive Programming",
  ITCS394: "Computer Network Programming",
  ITCS395: "Creative Programming",
  ITCS396: "Internship",
  ITCS397: "Cooperative Education",
  ITCS403: "Introduction to Healthcare Systems",
  ITCS404: "Information Technology for Healthcare Services",
  ITCS405: "Information Models and Healthcare Information Standards",
  ITCS407: "Practical Healthcare Management",
  ITCS409: "Special Topics in Healthcare Systems",
  ITCS410: "Practicum in Health Information Technology",
  ITCS412: "Social Network Analysis",
  ITCS415: "Deep Learning for Natural Language Processing",
  ITCS416: "Advanced Natural Language Processing",
  ITCS417: "Explainable Artificial Intelligence",
  ITCS418: "Special Topics in Artificial Intelligence and Data",
  ITCS419: "Deep Learning for Computer Vision",
  ITCS426: "Algorithms Design and Analysis",
  ITCS427: "Theory of Computation",
  ITCS430: "Special Topics in Information Systems",
  ITCS436: "Introduction to Parallel and High Performance Computing",
  ITCS440: "Principles of Compiler Design",
  ITCS441: "Information Retrieval and Text Mining",
  ITCS442: "Relational Database Design",
  ITCS444: "Data Mining",
  ITCS447: "Embedded Systems and Internet of Things",
  ITCS448: "Data Warehousing and Business Intelligence",
  ITCS449: "Introduction to Big Data Management",
  ITCS450: "Machine Learning with Big Data",
  ITCS454: "Special Topics in Database Systems",
  ITCS458: "Database Administration",
  ITCS460: "Introduction to Penetration Testing",
  ITCS462: "Internet of Things Security and Privacy",
  ITCS464: "Advanced Cybersecurity",
  ITCS466: "Local Area Network and Network Management",
  ITCS467: "Special Topics in Computer Networks, IoT and Cyber Security",
  ITCS468: "IT Auditing",
  ITCS469: "Wireless and IoT Networking",
  ITCS470: "Software Requirements Engineering",
  ITCS472: "Software Metrics",
  ITCS475: "Mathematical Programming",
  ITCS481: "Computer Graphics",
  ITCS489: "Independent Study",
  ITCS490: "Special Topics in Software Engineering",
  ITCS498: "Special Topics in Computer Science",
  ITCS499: "Cloud Computing Systems, Services and Applications",
};

export function lookupCourseName(code: string): string | null {
  return COURSE_NAMES[code.toUpperCase().replace(/\s+/g, "")] ?? null;
}
